In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
# from keras import backend as K

# Splitting the MNIST dataset into Train and Test

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
import numpy as np
np.set_printoptions(linewidth=1000)  # increase width

print(x_train.shape)
print(x_train[0].shape)

print(y_train[0])
print(x_train[0])

(60000, 28, 28)
(28, 28)
5
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253

# Preprocessing the input data

In [5]:
num_of_trainImgs = x_train.shape[0] #60000 here
num_of_testImgs = x_test.shape[0] #10000 here
img_width = 28
img_height = 28
 
x_train = x_train.reshape(x_train.shape[0], img_height, img_width, 1)
x_test = x_test.reshape(x_test.shape[0], img_height, img_width, 1)
print(x_train[0])
input_shape = (img_height, img_width, 1)
 
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [6]:


print(input_shape)

(28, 28, 1)


In [7]:
import numpy as np
np.set_printoptions(linewidth=1000)  # increase width

print(x_train.shape)
print(x_train[0].shape)

print(y_train[10000])
print(x_train[10000])

(60000, 28, 28, 1)
(28, 28, 1)
3
[[[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [

# Converting the class vectors to binary class

In [8]:
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Defining the model architecture

In [9]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))


c:\Users\debaa\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


# Compiling the model

In [10]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

# Fitting the model on training data

In [11]:
model.fit(x_train, y_train,
          batch_size=228,
          epochs=12,
          verbose=1,
          validation_data=(x_test, y_test))

Epoch 1/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 128s 466ms/step - accuracy: 0.1285 - loss: 2.2826 - val_accuracy: 0.1822 - val_loss: 2.2648
Epoch 2/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 142s 469ms/step - accuracy: 0.1833 - loss: 2.2560 - val_accuracy: 0.3113 - val_loss: 2.2331
Epoch 3/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 97s 368ms/step - accuracy: 0.2476 - loss: 2.2246 - val_accuracy: 0.4608 - val_loss: 2.1950
Epoch 4/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 134s 338ms/step - accuracy: 0.3140 - loss: 2.1866 - val_accuracy: 0.5697 - val_loss: 2.1477
Epoch 5/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 160s 408ms/step - accuracy: 0.3790 - loss: 2.1385 - val_accuracy: 0.6374 - val_loss: 2.0885
Epoch 6/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 176s 667ms/step - accuracy: 0.4365 - loss: 2.0793 - val_accuracy: 0.6791 - val_loss: 2.0128
Epoch 7/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 143s 442ms/step - accuracy: 0.4917 - loss: 2.0012 - val_accuracy: 0.7113 - val_loss: 1.9145
Epoch 8/12
264/264 ━━━━━━━━━━━━━━━━━━━━ 136s 418ms/step - accuracy: 0.5361 - 

#  Evaluating the model on test data

In [12]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 1.2154260873794556
Test accuracy: 0.7860000133514404


# Saving the Model

In [13]:
model.save('trained_model.h5')